spring:
  application:
    name: lesson9
  datasource:
    url: jdbc:mysql://localhost:3306/lesson9
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: library
    password: library
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
